[episodes] add getEpisodes method
Jxck/mozaic.fm pull request #47
Opened 2024-08-22 23:17 UTC by hiroppy

episodesを取得する関数を追加します。title, descriptionはmdをパースしfrontmatter(これしかexportされないので。。)へ挿入するremarkのpluginも追加します。

2024-08-22 23:21 UTC, hiroppy commented on next.config.mjs
> -  pageExtensions: ["js", "jsx", "md", "mdx", "ts", "tsx"],
ページとしてmdxを利用しないので削除

2024-08-22 23:21 UTC, hiroppy commented on remarkPlugins/updateFrontmatter.mjs
> +    visit(tree, "yaml", (node) => {
frontmatterのyamlを拡張し、import分でtitle, descriptionを取得できるようにする

2024-08-22 23:21 UTC, hiroppy commented on src/app/episodes/_utils/getEpisodes.test.ts
> +  // TODO
一旦、ブロッカーになってしまうのでこれは別のPRで対応します

2024-08-22 23:21 UTC, hiroppy commented on src/app/episodes/_utils/getEpisodes.ts
> +// webpackを通すと、まだnode:fs/promisesのglobが存在しないので、ライブラリを利用する
nodeのshimが対応してない。。。

2024-08-22 23:21 UTC, hiroppy commented on src/app/layout.tsx
> -export const runtime = "edge";
fsを利用するため、削除

2024-08-22 23:21 UTC, hiroppy commented on src/app/page.tsx
> +  // const tags = new Set(episodes.flatMap((episode) => episode.tags));
topの上にタグを表示する箇所があるので、一応おいておく

2024-08-22 23:21 UTC, hiroppy commented on tsconfig.json
> +    "target": "ES2023",
regexpのgroupsを利用するため、es2018以上にしておく。とりあえずこのサイトは最新でいいかって感じで2023にしておきました。。

2024-08-22 23:28 UTC, hiroppy commented on next.config.mjs
> +    remarkPlugins: [updateFrontmatter, remarkFrontmatter, remarkMdxFrontmatter],
この順序で最後に処理をするように

2024-08-25 06:01 UTC, Jxck requested changes
ちょっと細かいところ書いたけど、概ね方針は良さそう。

2024-09-02 12:41 UTC, Jxck requested changes

2024-09-02 12:41 UTC, Jxck commented on src/app/episodes/_utils/getEpisodes.ts
> +  return episodes.sort((a, b) => b.episode - a.episode);
コメントにも書いたけど、 Sideshow は ep が同じなのでそこだけみて。

先: https://mozaic.fm/episodes/63/cross-origin-info-leaks.html
後: https://mozaic.fm/episodes/63/cross-origin-info-leaks-sideshow.html

2024-09-02 12:50 UTC, hiroppy commented on src/app/episodes/_utils/getEpisodes.ts
> +  return episodes.sort((a, b) => b.episode - a.episode);
@Jxck こちらで！ https://github.com/Jxck/mozaic.fm/pull/47/commits/4ac1d07e6fad5529b03310e7aec5c40a2dda76ca

2024-09-02 12:51 UTC, Jxck commented
LGTM

2024-09-02 12:51 UTC, merged